### ISSUE TITLE
Frontend text is same color as background

### ISSUE THREAD

**Issue by CyrusVorwald** [kryptopoo/xcallscan#4] opened 2023-09-12 08:30 UTC
First off, thank you for submitting this project to the Incentivized xCall Testnet.

Onto the issue: I can't see the text unless I highlight it on https://testnet.xcallscan.xyz/ because the font color is too similar to the background. It would be helpful if it was black text or something that complies with the Web Content Accessibility Guidelines. You can use https://webaim.org/resources/contrastchecker/ to check if your text / background color schemes pass.

Example:
<img width="1375" alt="image" src="https://github.com/kryptopoo/xcallscan/assets/90732384/6b651d6e-e00d-47f3-913f-dfb767c1dfae">

<img width="1354" alt="image" src="https://github.com/kryptopoo/xcallscan/assets/90732384/ecd3924e-32f5-49d7-b1f8-63bd7e8b87cc">

**Comment by kryptopoo** [comment] 2023-09-16 02:49
@CyrusVorwald  oh it's so weird! I've checked on chrome, firefox and edge but didn't see this issue. Could you provide more detail about your environment? Or might be a cache issue on your browser?

![xcallscan-issue1-1](https://github.com/kryptopoo/xcallscan/assets/44108463/2ece4059-dc71-4054-a6be-9c8a2bd62949)
![xcallscan-issue1-2](https://github.com/kryptopoo/xcallscan/assets/44108463/11e6cf9b-9ef5-407b-96f1-416596d35c4e)
![xcallscan-issue1-3](https://github.com/kryptopoo/xcallscan/assets/44108463/f499ae79-ecd2-40b7-be1b-af800bfb23b7)

**Comment by izyak** [comment] 2023-09-28 09:28
Same issue for me too. Tried hard refreshing multiple times as well. I'm on linux machine.
## On firefox
![image](https://github.com/kryptopoo/xcallscan/assets/76203436/8a0969c3-e814-4146-9f59-dbae2ef897bc)

## On vivaldi
![image](https://github.com/kryptopoo/xcallscan/assets/76203436/38056d7b-2ea4-4667-a70e-ad5b69317a95)

**Comment by kryptopoo** [comment] 2023-10-04 09:36
@izyak @CyrusVorwald The root cause is theme conflict on dark mode of OS. It should be fixed soon.

**Closed** 2024-01-19 05:25 UTC
Labels: bug
